# add k8s/flyway-job.yaml as resources 

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - k8s/flyway-job.yaml

# TODO see if any way to add all files in a folder to configMap
configMapGenerator:
  - name: flyway-sql
    files:
      - sql/V1__Create_person_table.sql
      - sql/V2__Alter_person_table_add_country.sql
      - sql/V3__Insert_person.sql

secretGenerator:
  - name: flyway-config
    files:
      - k8s/flyway.conf